#服务器配置
server:
  port: 8088
  servlet:
    #统一前缀路径
    context-path: /

  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 16
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 400
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securityplatform?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    druid:
      validation-query: select 1
      validation-query-timeout: 2000
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 10
      filter:
        stat:
          log-slow-sql: true
  jpa:
    # 显示sql
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
  messages:
    basename: i18n/res
#    open-in-view: true

#系统自定义配置
cetc:
  #文件上传路径
  uploadFolder:
    path: D:/data/files/
    temp: D:/data/tempfiles/
  #token
  token:
    # 默认redis 设置为true后，token将存入redis，并具有单点登录功能 设为false将使用JWT交互
    redis: false
    # token中存储用户权限数据 设为true开启后可避免每次请求再获取用户权限，但有可能导致编辑权限菜单后无法读取到最新权限数据（需用户重新登录）
    storePerms: true
  # token过期时间（分钟）
  tokenExpireTime: 60
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  tenant:
    column: tenant_id
    tables:
      - t_notice
ignored:
  urls:
    - /editor-app/**
    - /cetc/act/**
    - /cetc/dictData/getByType/**
    - /cetc/email/sendResetCode
    - /cetc/email/resetByEmail
    - /cetc/file/view/**
    - /cetc/upload/**
    - /cetc/social/**
    - /cetc/ws/**
    - /cetc/user/regist
    - /cetc/user/smsLogin
    - /cetc/user/resetByMobile
    - /cetc/common/**
    - /cetc/flow/process/diagram-view
    - /druid/**
    - /swagger-ui.html
    - /swagger-resources/**
    - /swagger/**
    - /**/v2/api-docs
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /cetc/test/**
    - /cetc/app/**